name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    deployment_pipeline:
        runs-on: ubuntu-22.04
        env:
            TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
            PORT: ${{ secrets.PORT }}
            SECRET: ${{ secrets.SECRET }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install
            - name: lint
              run: npm run eslint
            - name: build
              run: npm run build
            # - name: Create env file
            #   run: |
            #       touch .env
            #       echo TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }} >> .env
            #       echo PORT=${{ secrets.PORT }} >> .env
            #       cat .env
            - name: test (jest)
              run: TEST_MONGODB_URI=$TEST_MONGODB_URI PORT=$PORT SECRET=$SECRET npm run test:jest
            - name: e2e tests
              uses: cypress-io/github-action@v5
              with:
                  command: npm run test:e2e
                  start: npm run start-prod
                  wait-on: http://localhost:3003
            - name: commit messages
              env:
                  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
              run: echo "$COMMIT_MESSAGES"

            - name: Trigger deployment
              if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
              run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

            - name: success notification
              if: ${{ success() && github.event_name == 'push' }}
              uses: rjstone/discord-webhook-notify@v1
              with:
                  severity: info
                  username: Github
                  # color: '#ff00aa'
                  avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
                  # description: This is a custom description.
                  details: 'to https://bloglist-hzdi.onrender.com/ by Kshitiz-Karki'
                  # footer: This is a footer.
                  text: A new version of bloglist app deployed
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

            - name: error notification
              if: ${{ failure() }}
              uses: rjstone/discord-webhook-notify@v1
              with:
                  # severity: info
                  username: Github
                  # color: '#ff00aa'
                  avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
                  # description: This is a custom description.
                  details: 'commit https://github.com/Kshitiz-Karki/full-stack-bloglist/commit/${{ github.sha }} broke the build :('
                  # footer: This is a footer.
                  text: Build failed
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    tag_release:
        needs: [deployment_pipeline]
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@1.67.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEFAULT_BUMP: patch
